import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  // variable: "--font-inter",
  // display: "swap",
  // weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Meet-AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
